In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
weather = pd.read_csv("//home/manoj/Desktop/Work/6th Sem/DSBDA/weather_data.csv")

In [3]:
weather.head(4)

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
0,San Diego,2024-01-14 21:12:46,10.683001,41.195754,4.020119,8.233540
1,San Diego,2024-05-17 15:22:10,8.734140,58.319107,9.111623,27.715161
2,San Diego,2024-05-11 09:30:59,11.632436,38.820175,4.607511,28.732951
3,Philadelphia,2024-02-26 17:32:39,-8.628976,54.074474,3.183720,26.367303

In [4]:
weather.tail(4)

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
999996,San Antonio,2024-01-20 15:59:48,6.759080,40.731036,8.182785,29.005558
999997,New York,2024-04-14 08:30:09,15.664465,62.201884,3.987558,0.403909
999998,Chicago,2024-05-12 20:10:43,18.999994,63.703245,4.294325,6.326036
999999,New York,2024-04-16 16:11:52,10.725351,43.804584,1.883292,15.363828

In [7]:
weather.index

RangeIndex(start=0, stop=1000000, step=1)

In [8]:
weather.columns

Index(['Location', 'Date_Time', 'Temperature_C', 'Humidity_pct',
       'Precipitation_mm', 'Wind_Speed_kmh'],
      dtype='object')

In [9]:
weather.shape

(1000000, 6)

In [10]:
weather.dtypes

Location             object
Date_Time            object
Temperature_C       float64
Humidity_pct        float64
Precipitation_mm    float64
Wind_Speed_kmh      float64
dtype: object

In [11]:
weather.columns.values

array(['Location', 'Date_Time', 'Temperature_C', 'Humidity_pct',
       'Precipitation_mm', 'Wind_Speed_kmh'], dtype=object)

In [7]:
weather.describe(include="all")

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
count,1000000,1000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
unique,10,959526,NaN,NaN,NaN,NaN
top,Phoenix,2024-04-25 08:19:00,NaN,NaN,NaN,NaN
freq,100209,4,NaN,NaN,NaN,NaN
mean,NaN,NaN,14.779705,60.021830,5.109639,14.997598
std,NaN,NaN,14.482558,17.324022,2.947997,8.663556
min,NaN,NaN,-19.969311,30.000009,0.000009,0.000051
25%,NaN,NaN,2.269631,45.008500,2.580694,7.490101
50%,NaN,NaN,14.778002,60.018708,5.109917,14.993777
75%,NaN,NaN,27.270489,75.043818,7.613750,22.514110
max,NaN,NaN,39.999801,89.999977,14.971583,29.999973

In [8]:
weather["Location"]

0            San Diego
1            San Diego
2            San Diego
3         Philadelphia
4          San Antonio
              ...
999995          Dallas
999996     San Antonio
999997        New York
999998         Chicago
999999        New York
Name: Location, Length: 1000000, dtype: object

In [16]:
weather.sort_index(axis = 1, ascending = False)
# axis = 0 means row and axis = 1 means column

,Date_Time,Humidity_pct,Location,Precipitation_mm,Temperature_C,Wind_Speed_kmh
0,2024-01-14 21:12:46,41.195754,San Diego,4.020119,10.683001,8.233540
1,2024-05-17 15:22:10,58.319107,San Diego,9.111623,8.734140,27.715161
2,2024-05-11 09:30:59,38.820175,San Diego,4.607511,11.632436,28.732951
3,2024-02-26 17:32:39,54.074474,Philadelphia,3.183720,-8.628976,26.367303
4,2024-04-29 13:23:51,72.899908,San Antonio,9.598282,39.808213,29.898622
...,...,...,...,...,...,...
999995,2024-01-01 20:29:48,37.705024,Dallas,3.819833,23.416877,16.538119
999996,2024-01-20 15:59:48,40.731036,San Antonio,8.182785,6.759080,29.005558
999997,2024-04-14 08:30:09,62.201884,New York,3.987558,15.664465,0.403909
999998,2024-05-12 20:10:43,63.703245,Chicago,4.294325,18.999994,6.326036
999999,2024-04-16 16:11:52,43.804584,New York,1.883292,10.725351,15.363828

In [11]:
weather.sort_values(by="Location")

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
499999,Chicago,2024-03-28 22:07:28,32.461429,37.561776,3.045372,17.365476
206635,Chicago,2024-04-24 04:00:37,8.058876,66.356581,8.794432,14.694489
206636,Chicago,2024-03-22 05:17:48,-9.566031,30.049724,3.659735,14.702168
751625,Chicago,2024-02-23 11:19:32,12.570231,56.262671,1.330531,15.889430
206640,Chicago,2024-03-05 14:06:20,2.233364,83.464227,8.305385,3.972172
...,...,...,...,...,...,...
669853,San Jose,2024-01-06 17:18:03,-7.703348,33.904461,2.128592,9.676672
72204,San Jose,2024-04-16 03:05:56,26.094373,57.874271,0.146885,12.594140
555115,San Jose,2024-05-18 09:07:50,10.901747,51.309752,5.536554,21.392218
370160,San Jose,2024-05-10 02:07:59,36.894416,47.353086,9.277973,28.031931
105279,San Jose,2024-03-11 00:17:29,28.920796,73.503884,7.145029,3.749138

In [22]:
weather.sort_values(by = "Temperature_C")

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
360894,Phoenix,2024-01-12 20:20:14,-19.969311,52.217649,0.554449,21.772620
152336,Phoenix,2024-01-24 22:23:25,-19.950223,42.893965,7.394094,15.847648
200629,Phoenix,2024-02-15 20:39:37,-19.847193,61.421469,14.666434,19.563713
4321,Phoenix,2024-01-18 17:40:21,-19.700813,57.039132,8.885283,24.649599
976565,Phoenix,2024-01-26 01:41:07,-19.684603,60.472683,4.059941,20.458349
...,...,...,...,...,...,...
998682,Los Angeles,2024-04-25 22:56:15,39.999592,36.665352,0.224281,20.169668
45231,Philadelphia,2024-05-16 04:02:09,39.999642,32.147664,6.733978,20.225895
394340,San Diego,2024-04-14 05:44:38,39.999670,58.520672,6.372076,20.814854
130221,San Diego,2024-01-29 15:18:50,39.999692,75.630696,3.217372,17.344337
899115,New York,2024-05-16 14:31:50,39.999801,35.418345,6.574819,20.988972

In [13]:
weather.loc[:, ["Date_Time", "Location", "Temperature_C"]]

             Date_Time      Location  Temperature_C
0  2024-01-14 21:12:46     San Diego      10.683001
1  2024-05-17 15:22:10     San Diego       8.734140
2  2024-05-11 09:30:59     San Diego      11.632436
3  2024-02-26 17:32:39  Philadelphia      -8.628976
4  2024-04-29 13:23:51   San Antonio      39.808213
5  2024-01-21 08:54:56     San Diego      27.341055

In [14]:
weather.iloc[:5, :]

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
0,San Diego,2024-01-14 21:12:46,10.683001,41.195754,4.020119,8.233540
1,San Diego,2024-05-17 15:22:10,8.734140,58.319107,9.111623,27.715161
2,San Diego,2024-05-11 09:30:59,11.632436,38.820175,4.607511,28.732951
3,Philadelphia,2024-02-26 17:32:39,-8.628976,54.074474,3.183720,26.367303
4,San Antonio,2024-04-29 13:23:51,39.808213,72.899908,9.598282,29.898622

In [15]:
weather.isnull()

,Location,Date_Time,Temperature_C,Humidity_pct,Precipitation_mm,Wind_Speed_kmh
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
999995,False,False,False,False,False,False
999996,False,False,False,False,False,False
999997,False,False,False,False,False,False
999998,False,False,False,False,False,False
999999,False,False,False,False,False,False

In [28]:
weather.isnull().any()

Location            False
Date_Time           False
Temperature_C       False
Humidity_pct        False
Precipitation_mm    False
Wind_Speed_kmh      False
dtype: bool

In [30]:
weather.isnull().sum()

Location            0
Date_Time           0
Temperature_C       0
Humidity_pct        0
Precipitation_mm    0
Wind_Speed_kmh      0
dtype: int64